### ISSUE TITLE
Unable to get access token 

### ISSUE THREAD

**Issue by wab-gl** [upwork/php-upwork-oauth2#19]
Unable to get access token 
After calling **\Upwork\API\Client([)** with **clientId** **clientSecret**  **redirectUri** and **code** to get redirected url with code and state in url parameter based on docs 
Uncaught Upwork\API\ApiException: Property [code] is unknown or can not be set. 

here my code snippet

```
$config = new \Upwork\API\Config(
    array(
        'clientId'          => 'xxxxxxxxxxxxxxxxx', 
        'clientSecret'      => 'xxxxxxxxxxxxxxxx',
        'grantType'         => 'xxxxxxxxxx', 
	      'redirectUri'       => 'xxxxxxxxxxxxxxxx',
        'debug'             => xxxx, 
        'code'          => 'xxxxxxxxxxxxx' 
    )
);

$client = new \Upwork\API\Client($config);
$accessTokenInfo = $client->auth();
print_r($accessTokenInfo);
```

**Comment by mnovozhylov** [comment]
@wab-gl , please, [contact Support Team](https://support.upwork.com/hc/en-us/articles/115015857627-API-error-handling) for further investigation.
