### ISSUE TITLE
Can you please help me understand this? " that you previously got"

### ISSUE THREAD

**Issue by jack-fdrv** [upwork/php-upwork-oauth2#4]
> open myapp.php and type the clientId, clientSecret and redirectUri that you previously got from the API Center. Please, read carefully the comments in the example.

What mean " that you previously got", got how? I should first get something to use this library?

Also, seems it require, accessToken, refreshToken, expiresIn. 
How I can get it?

> In addition to this, a full example is available in the example directory. This includes example.php that gets an access token and requests the data.

So this script should already get the tokens, but how?

**Comment by mnovozhylov** [comment]
@jack-fdrv , please, follow the official Upwork API documentation at https://developers.upwork.com/?lang=php#getting-started

Also, note that `OAuth2` authentication is NOT shared for public usage. So, if you don't participate as a beta tester, you need to use the library for `OAuth1`, which can be found here https://github.com/upwork/php-upwork
