### ISSUE TITLE
After installing I see this

### ISSUE THREAD

**Issue by jack-fdrv** [upwork/php-upwork-oauth2#5]
![image](https://user-images.githubusercontent.com/4230282/71546621-99800980-29a1-11ea-862c-7bed8b1d5ae6.png)

**Comment by mnovozhylov** [comment]
Judging by https://github.com/upwork/php-upwork-oauth2/issues/4 (other "issue" you filled), you don't use key/token and receive a valid response from the server about unauthorized request. Thus, I assume the library works as expected.
