### ISSUE TITLE
How do you get OAuth 2.0 acces credentials from UpWork?

### ISSUE THREAD

**Issue by Pixelalb** [upwork/php-upwork-oauth2#7]
...they only provide OAuth 1.0 here: https://www.upwork.com/services/api/apply

Thank you!

**Comment by mnovozhylov** [comment]
That's a wrong place for such questions. Please, check https://developers.upwork.com/#authentication-beta_oauth-20 , and contact Support Team if needed.

**Comment by Pixelalb** [comment]
I understand that and sorry that this is not related to this project specifically. I've tried to get in touch with them (they're very slow to answer) ... 

Since you're describing the use of the OAuth v2 in your project, I thought that you've already gone through the process of obtaining OAuth v2 credentials from Upwork and that you could just share that experience (that be awesome!) 

Thank you again and sorry for the offtopic topic :)
